services: docker
language: bash

env:
  global:
    - IMAGE_PREFIX=${IMAGE_PREFIX:-$DOCKER_USER/}
    - PUSH_LIST=/tmp/push_list
  matrix:
    - SUBDIR=server/libev/2.4 TAG_PREFIX="server-"
    - SUBDIR=forward/1.6 TAG_PREFIX="forward-"
    - SUBDIR=client/libev/2.4 TAGS="latest"

script:
  - ./build.sh

after_script:
  - docker images
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" -e "$DOCKER_EMAIL"
  - for x in $(cat "$PUSH_LIST"); do docker push $x; done
